"""
Medical abbreviation expansion table.
Covers common clinical/pharmacological abbreviations used in discharge summaries.
Context-sensitive expansions use the longest-match principle.
"""

# Format: abbreviation (case-insensitive key) → full expansion
# Longer / more specific keys must appear first to get priority.

ABBREVIATIONS: dict[str, str] = {
    # ── Vital signs & monitoring ──────────────────────────────────────────
    "VS":      "vital signs",
    "BP":      "blood pressure",
    "HR":      "heart rate",
    "RR":      "respiratory rate",
    "SpO2":    "oxygen saturation",
    "SaO2":    "oxygen saturation",
    "O2":      "oxygen",
    "2L O2":   "2 liters of supplemental oxygen",
    "2L":      "2 liters",
    "3L":      "3 liters",
    "RA":      "room air",
    "ra":      "room air",
    "Tm":      "maximum temperature",
    "Tc":      "current temperature",
    "NAD":     "no acute distress",
    "WNL":     "within normal limits",

    # ── Physical exam ─────────────────────────────────────────────────────
    "HEENT":   "head, eyes, ears, nose, and throat",
    "NCAT":    "normocephalic and atraumatic",
    "PERRL":   "pupils equal, round, and reactive to light",
    "PERRLA":  "pupils equal, round, reactive to light and accommodation",
    "EOMI":    "extraocular movements intact",
    "JVD":     "jugular venous distension",
    "JVP":     "jugular venous pressure",
    "LAD":     "lymphadenopathy",
    "HSM":     "hepatosplenomegaly",
    "NTND":    "non-tender, non-distended",
    "c/c/e":   "clubbing, cyanosis, or edema",
    "RRR":     "regular rate and rhythm",
    "S1":      "first heart sound",
    "S2":      "second heart sound",
    "M/R/G":   "murmurs, rubs, or gallops",
    "SOB":     "shortness of breath",
    "DOE":     "dyspnea on exertion",
    "PND":     "paroxysmal nocturnal dyspnea",
    "OP":      "oropharynx",
    "OM":      "oral mucosa",
    "MMM":     "moist mucous membranes",

    # ── Diagnoses / conditions ────────────────────────────────────────────
    "COPD":    "chronic obstructive pulmonary disease",
    "CAD":     "coronary artery disease",
    "HTN":     "hypertension",
    "htn":     "hypertension",
    "Afib":    "atrial fibrillation",
    "AFib":    "atrial fibrillation",
    "afib":    "atrial fibrillation",
    "AF":      "atrial fibrillation",
    "RVR":     "rapid ventricular response",
    "PAD":     "peripheral arterial disease",
    "PVD":     "peripheral vascular disease",
    "ACS":     "acute coronary syndrome",
    "CHF":     "congestive heart failure",
    "HF":      "heart failure",
    "MI":      "myocardial infarction",
    "PE":      "pulmonary embolism",
    "DVT":     "deep vein thrombosis",
    "LBBB":    "left bundle-branch block",
    "URI":     "upper respiratory infection",
    "PNA":     "pneumonia",
    "AKI":     "acute kidney injury",
    "CKD":     "chronic kidney disease",
    "DM":      "diabetes mellitus",
    "DM2":     "type 2 diabetes mellitus",
    "HLD":     "hyperlipidemia",
    "OSA":     "obstructive sleep apnea",
    "GERD":    "gastroesophageal reflux disease",
    "GIB":     "gastrointestinal bleeding",
    "EF":      "ejection fraction",
    "WBC":     "white blood cell count",
    "RBC":     "red blood cell count",
    "Hgb":     "hemoglobin",
    "HGB":     "hemoglobin",
    "Hct":     "hematocrit",
    "HCT":     "hematocrit",
    "MCV":     "mean corpuscular volume",
    "MCH":     "mean corpuscular hemoglobin",
    "MCHC":    "mean corpuscular hemoglobin concentration",
    "RDW":     "red cell distribution width",
    "Plt":     "platelet count",
    "BNP":     "brain natriuretic peptide",
    "proBNP":  "pro-brain natriuretic peptide",
    "TSH":     "thyroid-stimulating hormone",
    "T4":      "thyroxine",
    "cTropnT": "cardiac troponin T",
    "CK-MB":   "creatine kinase-MB isoenzyme",
    "Trop":    "troponin",
    "Na":      "sodium",
    "K":       "potassium",
    "Cl":      "chloride",
    "HCO3":    "bicarbonate",
    "CO2":     "carbon dioxide",
    "BUN":     "blood urea nitrogen",
    "UreaN":   "blood urea nitrogen",
    "Creat":   "creatinine",
    "Cr":      "creatinine",
    "AnGap":   "anion gap",
    "Mg":      "magnesium",
    "Phos":    "phosphorus",
    "Ca":      "calcium",
    "ALT":     "alanine aminotransferase",
    "AST":     "aspartate aminotransferase",
    "AlkPhos": "alkaline phosphatase",
    "TotBili": "total bilirubin",
    "Albumin": "serum albumin",
    "pO2":     "partial pressure of oxygen",
    "pCO2":    "partial pressure of carbon dioxide",
    "pH":      "blood pH",
    "calTCO2": "calculated total carbon dioxide",
    "Base XS": "base excess",
    "TIBC":    "total iron-binding capacity",
    "calTIBC": "calculated total iron-binding capacity",
    "Ferritn": "ferritin",
    "TRF":     "transferrin",
    "PTT":     "partial thromboplastin time",
    "INR":     "international normalized ratio",
    "H/H":     "hemoglobin and hematocrit",
    "PFTs":    "pulmonary function tests",
    "EKG":     "electrocardiogram",
    "ECG":     "electrocardiogram",
    "CXR":     "chest X-ray",
    "CTA":     "computed tomography angiography",
    "CT":      "computed tomography",
    "MRI":     "magnetic resonance imaging",
    "MR":      "magnetic resonance",
    "MRA":     "magnetic resonance angiography",
    "ADC":     "apparent diffusion coefficient",
    "ECHO":    "echocardiogram",
    "TTE":     "transthoracic echocardiogram",
    "QTc":     "corrected QT interval",
    "QT":      "QT interval",
    "NIHSS":   "National Institutes of Health Stroke Scale",
    "TIA":     "transient ischemic attack",
    "CVA":     "cerebrovascular accident",
    "L MCA":   "left middle cerebral artery",
    "R MCA":   "right middle cerebral artery",
    "MCA":     "middle cerebral artery",

    # ── Procedures / history ──────────────────────────────────────────────
    "s/p":     "status post",
    "h/o":     "history of",
    "hx":      "history",
    "Hx":      "history",
    "pmhx":    "past medical history",
    "PMHx":    "past medical history",
    "PMH":     "past medical history",
    "ED":      "emergency department",
    "EMS":     "emergency medical services",
    "EMT":     "emergency medical technician",
    "OSH":     "outside hospital",
    "ICU":     "intensive care unit",
    "PCP":     "primary care physician",
    "IV":      "intravenous",
    "PO":      "by mouth (orally)",
    "SQ":      "subcutaneous",
    "IM":      "intramuscular",
    "IH":      "inhaled",
    "INH":     "inhaled",
    "NEB":     "nebulizer",
    "Neb":     "nebulizer",
    "neb":     "nebulizer",
    "nebs":    "nebulizer treatments",
    "Soln":    "solution",
    "Ophth":   "ophthalmic",
    "gtt":     "intravenous drip (guttae)",
    "PPX":     "prophylaxis",
    "PPx":     "prophylaxis",

    # ── Medication / dosing sigs ──────────────────────────────────────────
    "BID":     "twice daily",
    "bid":     "twice daily",
    "TID":     "three times daily",
    "QID":     "four times daily",
    "QD":      "once daily",
    "DAILY":   "once daily",
    "QHS":     "every bedtime",
    "QAM":     "every morning",
    "QPM":     "every evening",
    "Q4H":     "every 4 hours",
    "Q2H":     "every 2 hours",
    "q2h":     "every 2 hours",
    "Q6H":     "every 6 hours",
    "q6h":     "every 6 hours",
    "Q8H":     "every 8 hours",
    "Q12H":    "every 12 hours",
    "Q24H":    "every 24 hours",
    "q3d":     "every 3 days",
    "PRN":     "as needed",
    "prn":     "as needed",
    "Disp":    "dispense",
    "Rx":      "prescription",
    "RX":      "prescription",
    "mg":      "milligrams",
    "mcg":     "micrograms",
    "mL":      "milliliters",
    "TAB":     "tablet",
    "CAP":     "capsule",
    "SPRY":    "spray",
    "DROP":    "drop",
    "NU":      "nasal",
    "SS":      "single-strength",
    "ER":      "extended-release",
    "SR":      "sustained-release",
    "XR":      "extended-release",
    "DR":      "delayed-release",
    "ASDIR":   "as directed",
    "HS":      "every bedtime",
    "UNIT":    "unit",

    # ── Common drug abbreviations ─────────────────────────────────────────
    "HCTZ":    "hydrochlorothiazide",
    "ASA":     "aspirin",
    "APAP":    "acetaminophen",
    "PPI":     "proton pump inhibitor",
    "H2B":     "H2-blocker",
    "LABA":    "long-acting beta agonist",
    "SABA":    "short-acting beta agonist",
    "ICS":     "inhaled corticosteroid",

    # ── Miscellaneous clinical ────────────────────────────────────────────
    "A&Ox3":   "alert and oriented to person, place, and time",
    "A&O":     "alert and oriented",
    "CN":      "cranial nerve",
    "c/w":     "consistent with",
    "c/f":     "concern for",
    "C/F":     "concern for",
    "otpt":    "outpatient",
    "b/l":     "bilateral",
    "B/L":     "bilateral",
    "nl":      "normal",
    "d/c":     "discharge",
    "w/":      "with",
    "W/CONTRAST": "with contrast",
    "W & W/O CONTRAST": "with and without contrast",
    "w/o":     "without",
    "W/O CONTRAST": "without contrast",
    "W/O":     "without",
    "r/o":     "rule out",
    "R/O":     "rule out",
    "dx":      "diagnosis",
    "Dx":      "diagnosis",
    "tx":      "treatment",
    "Tx":      "treatment",
    "sx":      "symptoms",
    "Sx":      "symptoms",
    "hx":      "history",
    "f/u":     "follow-up",
    "F/U":     "follow-up",
    "yo":      "year-old",
    "y/o":     "year-old",
    "yo F":    "year-old female",
    "yo M":    "year-old male",
    "F":       "female",   # only used in structured fields
    "M":       "male",
    "HCP":     "healthcare proxy",
    "DNR":     "do not resuscitate",
    "DNI":     "do not intubate",
    "CMO":     "comfort measures only",
}
